name: ci
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - name: Run tests
        id: test-tox
        run: |
          uv run --locked tox
      - name: Persist test failure snapshots
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: snapshot_tests_failures
          # Using a wildcard causes path prefixes before the wildcard to be stripped
          path: tests/snapshot_tests_failures/*
        if: ${{ failure() && steps.test-tox.conclusion == 'failure' && hashFiles('tests/snapshot_tests_failures/**/*') != '' }}

  test-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - name: Build and test
        run: |
          npm ci
          npm run build
          npm run test
