name: generate-snapshots
on: workflow_dispatch
permissions:
  contents: read
jobs:
  generate-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Update snapshots
        run: |
          uv run tox -e test -- --update-snapshots
        continue-on-error: true
      - name: Upload snapshots
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: snapshots
          path: tests/snapshots
