name: generate-snapshots
on: workflow_dispatch
permissions:
  contents: read
jobs:
  generate-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Update snapshots
        run: |
          uv run tox -e test -- --update-snapshots
        continue-on-error: true
      - name: Upload snapshots
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: snapshots
          path: tests/snapshots
